### ISSUE TITLE
Code Licence

### ISSUE THREAD

**Issue by hskrtich** [kcmerrill/fetch-proxy#24]
Please add a Licence of some sort to this repo. I would prefer the MIT licence.

**Comment by kcmerrill** [comment]
@bskrtich I think at this point, given the back and fourth, it would probably be best if RP used https://github.com/containous/traefik. Or feel free and fork this repo at the commit Id I referenced earlier in the previous comment. 

Traefik I think would be a drop in replacement for you.

**Comment by kcmerrill** [comment]
^^^ whoops. wrong issue. 

I added a license.
