### ISSUE TITLE
Proxy registers the incorrect port

### ISSUE THREAD

**Issue by mkenney** [kcmerrill/fetch-proxy#27]
Hey KC!

I've been running into some issues with `fetch-proxy` inconsistently sending traffic to the wrong port when I have multiple port options.

I have a service with a following port setup:

```yaml
ports:
    - 80
    - 50051
```

The reason is that the service is serving both a REST api and a gRPC service. What I see happening is `fetch-proxy` will arbitrarily select which port it registers with a particular container name and often will end up sending all my REST requests to the gRPC port. Is there a way to specify which port the proxy should register with a container?

**Comment by kcmerrill** [comment]
Yeah, maps in golang are silly silly things. 

https://github.com/kcmerrill/fetch-proxy/blob/master/docker.go#L34

We could either whitelist all the 80/8080 styled web ports and choose only those _OR_ you can use port 443(if not in production with encryption) to ignore it as a quick workaround.

Is this for work or for pleasure?

**Comment by mkenney** [comment]
It's for work, the 443 thing should work fine for the moment. I think preferring web ports on the `PrivatePort` probably makes the most sense in general. I can send you a PR if you want, do you care how the ports are picked?

**Comment by kcmerrill** [comment]
No, a PR would be great!

**Comment by kcmerrill** [comment]
Can you also white list 3000 and 5000(node/ruby web ports) too pretty please?

**Comment by mkenney** [comment]
Will do!

**Comment by mkenney** [comment]
#28 is up.

**Comment by kcmerrill** [comment]
hey duder, thanks for the PR! 

Merged and pushed the latest and greatest to dockerhub. I didn't do any testing so 🤞

**Comment by mkenney** [comment]
w00t! It's so far so good for me, thanks,

```
time="2018-06-26T17:15:20.059Z" host="fetch-proxy" level="debug" msg="initial port selected" Container="auth.app" Private="50051" Public="33482" caller="docker.go:50 main.ContainerWatch"
time="2018-06-26T17:15:20.059Z" host="fetch-proxy" level="debug" msg="prioritized port selected" Container="auth.app" Private="80" Public="33483" caller="docker.go:61 main.ContainerWatch"
time="2018-06-26T17:15:20.059Z" host="fetch-proxy" level="info"  msg="Registered endpoint" registered="auth.app" url="http://172.26.0.1:33483" urlbase="auth.app" caller="proxy.go:105 main.AddSite"
```
